{
  "cells": [
    {
      "cell_type": "markdown",
      "id": "9390a499-b04f-452e-891a-07bfbcc31e95",
      "metadata": {
        "id": "9390a499-b04f-452e-891a-07bfbcc31e95",
        "tags": []
      },
      "source": [
        "# Use ellipticbn to measure the ellipticity of cucurbituril hosts\n",
        "\n",
        "\n",
        "### Description\n",
        "\n",
        "*ElliptiCBn is a collaboration between the Pluth and Harms labs at the University of Oregon*\n",
        "\n",
        "Arman Garcia, Michael Shavlik PhD, Mike Harms PhD, Mike Pluth PhD\n",
        "\n",
        "A manuscript describing the software is forthcoming.\n",
        "\n",
        "\n",
        "\n",
        "#### ellipticbn performs the following steps\n",
        "\n",
        "<img src=\"https://github.com/harmsm/ElliptiC/raw/main/images/pipeline_image.png\" width=\"600px\"/>\n",
        "\n",
        "1. Extract the coordinates of all C, N, O, and H atoms from an xyz file.\n",
        "\n",
        "2. Identify separate molecules by finding strongly-connected components.\n",
        "\n",
        "3. Identify macrocycles using patterns of bonds, cycle connectivity and cycle size. \n",
        "\n",
        "5. Use a Principal Component Analysis to calculate the variance along both major axes of the central cycle.\n",
        "\n",
        "6. Calculate ellipticity. This is done by two methods:\n",
        "\n",
        "   A.  *pca_ellip*: $(V_{ax1}-V_{ax2})/V_{ax1}$ where $V_{ax1}$ is the PCA variance on the longest axis (length) and $V_{ax2}$ is the PCA variance on the second-longest axis (width).  \n",
        "\n",
        "   B.  *orig_ellip*: Use the perimeter and largest carbon-to-centroid distance to infer ellipticity.\n",
        "\n",
        "7. Generate outputs, which include annotated structures and a spreadsheet with ellipticities.\n",
        "\n",
        "### Input\n",
        "\n",
        "ElliptiCBn takes molecular structures in [XYZ format](https://en.wikipedia.org/wiki/XYZ_file_format). The first two lines are ignored. We assume the coordinates are in angstroms. XYZ files can be generated from other structure formats using software like [Open Babel](http://openbabel.org). "
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "id": "61b0c513-15e2-4771-a9ff-4fb40a397911",
      "metadata": {
        "cellView": "form",
        "id": "61b0c513-15e2-4771-a9ff-4fb40a397911"
      },
      "outputs": [],
      "source": [
        "#@title Set up environment\n",
        "\n",
        "#@markdown This cell configures the computing environment to run ellipticbn. Run\n",
        "#@markdown this cell before uploading an XYZ file.\n",
        "\n",
        "#@markdown To run the cell, click the \"Play\" button to the left.\n",
        "\n",
        "try:\n",
        "    import google.colab\n",
        "    RUNNING_IN_COLAB = True\n",
        "except ImportError:\n",
        "    RUNNING_IN_COLAB = False\n",
        "except Exception as e:\n",
        "    err = \"Could not figure out if runnning in a colab notebook\\n\"\n",
        "    raise Exception(err) from e\n",
        "\n",
        "if RUNNING_IN_COLAB:\n",
        "    !git clone https://github.com/harmslab/ellipticbn\n",
        "    %cd ellipticbn\n",
        "    %pip install . pyproject.toml \n",
        "\n",
        "# ------------------------------------------------------------------------------\n",
        "# Imports\n",
        "\n",
        "import ellipticbn as ec\n",
        "\n",
        "import numpy as np\n",
        "import pandas as pd\n",
        "\n",
        "import shutil\n",
        "import os\n",
        "import inspect\n",
        "import re\n",
        "\n",
        "# Set these here in case the user does not run the cell below.\n",
        "min_num_carbons = 10 \n",
        "max_num_carbons = 20 \n",
        "guest_search_radius = 3 \n",
        "output_dir = \".\"\n",
        "overwrite = False\n",
        "\n",
        "# Note that we're getting get_macrocycles doc string because this has the\n",
        "# relevant user-settable parameters for a colab-level user. If someone wants\n",
        "# to set parameters to ec.run_all, they can run help on that within a\n",
        "# python environment.\n",
        "print(\"\\nParameter descriptions\\n\")\n",
        "doc_string = dict(inspect.getmembers(ec.get_macrocycles))[\"__doc__\"]\n",
        "doc_string = doc_string.split(\"Returns\")[0]\n",
        "\n",
        "lines = doc_string.split(\"\\n\")\n",
        "\n",
        "print(\"\\n\".join(lines[7:]))"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "id": "94f6cb28-6997-4dbf-a6e7-9e7a46a1756a",
      "metadata": {
        "cellView": "form",
        "id": "94f6cb28-6997-4dbf-a6e7-9e7a46a1756a"
      },
      "outputs": [],
      "source": [
        "#@title Set calculation parameters\n",
        "\n",
        "#@markdown The default parameters should work for most calculations, but you can\n",
        "#@markdown edit them if necessary to pull out the correct macrocycles. After\n",
        "#@markdown setting the parameters, press the \"Play\" button on the left before\n",
        "#@markdown proceeding. Parameter descriptions are above.\n",
        "\n",
        "min_num_carbons = 10 #@param\n",
        "max_num_carbons = 20 #@param\n",
        "guest_search_radius = 3 #@param\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "id": "d83a8807-144d-494e-904d-648623420e80",
      "metadata": {
        "cellView": "form",
        "id": "d83a8807-144d-494e-904d-648623420e80"
      },
      "outputs": [],
      "source": [
        "#@title Upload a file and run analysis\n",
        "\n",
        "#@markdown You can either upload a single .xyz file OR a .zip file containing\n",
        "#@markdown multiple .xyz files.\n",
        "\n",
        "#@markdown Press the \"Play\" button do upload the file.\n",
        "\n",
        "\n",
        "if RUNNING_IN_COLAB:\n",
        "\n",
        "    f = google.colab.files.upload()\n",
        "    filename = list(f.keys())[0]\n",
        "\n",
        "    out_base = f\"{filename}_out\"\n",
        "    if not os.path.isdir(out_base):\n",
        "        os.mkdir(out_base)\n",
        "\n",
        "    if filename.split(\".\")[-1].lower() == \"zip\":\n",
        "\n",
        "        input_dir = \".\".join(filename.split(\".\")[:-1])\n",
        "\n",
        "        shutil.unpack_archive(filename,input_dir)\n",
        "\n",
        "        match_pattern = re.compile(\"\\.xyz\",re.IGNORECASE)\n",
        "        file_input = []\n",
        "        for root, dir, files in os.walk(input_dir):\n",
        "            for f in files:\n",
        "                if f.startswith(\"._\"):\n",
        "                    continue\n",
        "                if not match_pattern.search(f):\n",
        "                    continue\n",
        "\n",
        "                file_input.append(os.path.join(root,f))\n",
        "\n",
        "        file_input.sort()\n",
        "\n",
        "        output_dir = f\"{input_dir}_output\"\n",
        "\n",
        "    else:\n",
        "\n",
        "        input_dir = \".\".join(filename.split(\".\")[:-1])\n",
        "        file_input = [filename]\n",
        "        output_dir = f\"{input_dir}_output\"\n",
        "\n",
        "fig = ec.run_all(file_input,\n",
        "                 min_num_carbons=min_num_carbons,\n",
        "                 max_num_carbons=max_num_carbons,\n",
        "                 guest_search_radius=guest_search_radius,\n",
        "                 output_dir=output_dir,\n",
        "                 overwrite=overwrite)\n",
        "\n",
        "if fig is not None:\n",
        "    fig.show()\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "id": "cbe008f5-12c1-4673-817b-c126bc598305",
      "metadata": {
        "cellView": "form",
        "id": "cbe008f5-12c1-4673-817b-c126bc598305"
      },
      "outputs": [],
      "source": [
        "#@title Download results\n",
        "\n",
        "#@markdown To download the results, press the \"Play\" button on the left.\n",
        "#@markdown The zip file will have a spreadsheet with the calculated\n",
        "#@markdown ellipticities, as well as an html file showing the ellipses\n",
        "#@markdown graphically.\n",
        "\n",
        "if RUNNING_IN_COLAB:\n",
        "\n",
        "    shutil.make_archive(base_name=output_dir,\n",
        "                        format=\"zip\",\n",
        "                        base_dir=output_dir)\n",
        "    print(f\"Put results in {output_dir}.zip\")\n",
        "\n",
        "    google.colab.files.download(f\"{output_dir}.zip\")"
      ]
    }
  ],
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "display_name": "Python 3 (ipykernel)",
      "language": "python",
      "name": "python3"
    },
    "language_info": {
      "codemirror_mode": {
        "name": "ipython",
        "version": 3
      },
      "file_extension": ".py",
      "mimetype": "text/x-python",
      "name": "python",
      "nbconvert_exporter": "python",
      "pygments_lexer": "ipython3",
      "version": "3.9.12"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 5
}
